-- CreateTable
CREATE TABLE "client_intake_forms" (
    "id" SERIAL NOT NULL,
    "client_name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone_number" TEXT NOT NULL,
    "event_date" TIMESTAMP(3) NOT NULL,
    "event_type" TEXT NOT NULL,
    "venue_location" TEXT NOT NULL,
    "guest_count" INTEGER NOT NULL,
    "event_duration" TEXT NOT NULL,
    "event_start_time" TEXT NOT NULL,
    "event_end_time" TEXT NOT NULL,
    "music_genres" TEXT[],
    "music_era" TEXT NOT NULL,
    "volume_preference" TEXT NOT NULL,
    "must_play_songs" TEXT NOT NULL,
    "must_play_spotify_url" TEXT,
    "must_play_apple_music_url" TEXT,
    "must_play_other_url" TEXT,
    "do_not_play_songs" TEXT NOT NULL,
    "do_not_play_spotify_url" TEXT,
    "do_not_play_apple_music_url" TEXT,
    "do_not_play_other_url" TEXT,
    "special_announcements" TEXT,
    "first_dance_song" TEXT,
    "last_dance_song" TEXT,
    "ceremony_songs" TEXT,
    "equipment_requests" TEXT,
    "setup_requirements" TEXT,
    "special_requests" TEXT,
    "dietary_restrictions" TEXT,
    "accessibility_needs" TEXT,
    "submitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "client_intake_forms_pkey" PRIMARY KEY ("id")
);
